name: Lint

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'C:\\Users\\runneradmin\\.m2\\repository'
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml
          
    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: 'master'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
